Fix pre commit issues
cameds58/gdp_repo_structure pull request #8
Opened 2024-11-05 01:35 UTC by ty338jy

@yuanjingshi @ps2016-mt 

Hello guys, please review the fix for pre-commit run, fixes including:
- line of codes should have characters less than 78
- functions should be 2 blank lines apart from each other
- mypy is running issue with request (missing library stubs)
1. mypy.ini was created to set ignore_missing_imports =True
2. pre-commit-config.yaml was updated

2024-11-05 06:43 UTC, yuanjingshi requested changes

2024-11-05 06:43 UTC, yuanjingshi commented on mypy.ini
Maybe to add a comment of why ignore imports missing.

2024-11-05 08:21 UTC, ty338jy commented on mypy.ini
Hey Yuanjing,
Comments added as requested!

2024-11-05 14:29 UTC, yuanjingshi approved these changes, later dismissed
Looks very good. I like your clear description in the PR. I shall learn from you on that.

2024-11-05 20:08 UTC, ps2016-mt commented
agreed, looks good!

2024-11-05 20:13 UTC, ps2016-mt approved these changes, later dismissed
agreed, looks good!

2024-11-05 20:39 UTC, ps2016-mt submitted a review, later dismissed
merge base seems fine with me

2024-11-05 20:41 UTC, cameds58 approved these changes

2024-11-05 20:41 UTC, cameds58 approved these changes, later dismissed

2024-11-05 22:38 UTC, yuanjingshi submitted a review, later dismissed

2024-11-06 15:55 UTC, jps215 approved these changes
Looks good

2024-11-06 16:01 UTC, yuanjingshi approved these changes, later dismissed

2024-11-06 16:36 UTC, cameds58 submitted a review, later dismissed

2024-11-06 16:39 UTC, merged